trigger:
- main   # Change this to the branch you want to trigger the build

pool:
  name: Windows_Pool
  demands:
    - maven    # Make sure the agent in the pool has Maven installed

jobs:
- job: Build
  displayName: 'Build Maven Project'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'path/to/your/pom.xml'  # Adjust the path based on your project structure
      goals: 'clean install'
      options: '-Xmx3072m'   # Optional: Adjust JVM memory settings as needed
      publishJUnitResults: true
    displayName: 'Build and test'

  # Additional steps can be added here, such as deploying artifacts, running additional tests, etc.
